#!/usr/bin/env python

import nmap

hlist = 'hostlist.txt'

# initialize the port scanner
nm = nmap.PortScanner()

with open(hlist) as f:
    for line in f:
        nm.scan(line, '1-2024', arguments='-O --script ssl-enum-ciphers,ssh2-enum-algos')
        #'--script=/usr/share/nmap/scripts/ssl-enum-ciphers.nse')
        print(nm.command_line())
        for host in nm.all_hosts():
            print('-----------------------------------------')
            print('Host : {} ({})'.format(host, nm[host].hostname()))
            print('State : {}'.format(nm[host].state()))
            for proto in nm[host].all_protocols():
                print('----------')
                print('Protocol : {}'.format(proto))
            
                lport = nm[host][proto].keys()
                for port in lport:
                    print ('port : {}\tstate : {}'.format(port, nm[host][proto][port]['state']))

            
            for nm[host].has_key('osclass'):
                for osclass in nm[host]['osclass']:
                    print('OsClass.type : {0}'.format(osclass['type']))
                    print('OsClass.vendor : {0}'.format(osclass['vendor']))
                    print('OsClass.osfamily : {0}'.format(osclass['osfamily']))
                    print('OsClass.osgen : {0}'.format(osclass['osgen']))
                    print('OsClass.accuracy : {0}'.format(osclass['accuracy']))
                    print('')

                if nm[line].has_key('osmatch'):
                    for osmatch in nm[host]['osmatch']:
                        print('osmatch.name : {0}'.format(osmatch['name']))
                        print('osmatch.accuracy : {0}'.format(osmatch['accuracy']))
                        print('osmatch.line : {0}'.format(osmatch[host]))
                        print('')

